require "date"

Vagrant.require_version ">= 1.6.2"

# Resolve paths before passing them to config.vm.provision
# I do this because, when run from my buildlab.ps1 script, I set ENV:VAGRANT_CWD to this directory,
# but pushd away into a working directory on a bigger disk for actually keeping the VM
thisVagrantfileDir = File.dirname(__FILE__)
commonScriptsDir = "#{thisVagrantfileDir}/../../scripts"

cpuCount = 2
memCount = 4096

Vagrant.configure("2") do |config|
    config.vm.define "FreyjaA-2017-07-18"
    config.vm.box = "wintriallab-win2016-64"
    config.vm.box_url = "file:///C:/Users/mledbetter/Documents/Vagrant/wintriallab-win2016-64.json"
    config.vm.communicator = "winrm"
    config.winrm.username = "vagrant"
    config.winrm.password = "V@grant123"
    config.vm.guest = :windows
    config.windows.halt_timeout = 15

    # One of the VPNs I have to use will only work with a bridged connection
    # However, Vagrant apparently doesn't like this, so unless you do :adapter=>1 it will create a second adapter
    # More investigation is required... the :adapter=>1 line hasn't been tested yet
    # For now: require switching to bridged connection manually after 'vagrant up'
    #config.vm.network :public_network
    #config.vm.network :public_network, :adapter=>1, type:"dhcp", :bridge=>'Ethernet'

    config.vm.network :public_network, :adapter=>1, type:"dhcp", :bridge=>'HyperVWifiSwitch'
    # config.vm.network :forwarded_port, guest: 3389, host: 3301, id: "rdp", auto_correct: true

    config.vm.provider :virtualbox do |v, override|
        #v.gui = true
        v.customize ["modifyvm", :id, "--memory", memCount]
        v.customize ["modifyvm", :id, "--cpus", cpuCount]
        v.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
        v.customize ["modifyvm", :id, "--accelerate2dvideo", "on"]
        v.customize ["modifyvm", :id, "--vram", 128]
        v.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
        v.customize ["modifyvm", :id, "--draganddrop", "bidirectional"]
    end
    config.vm.provider "hyperv" do |h|
        h.cpus = cpuCount
        h.memory = memCount
        h.differencing_disk = true
    end

    # config.vm.synced_folder "#{ENV['USERPROFILE']}\\Downloads", "/HostDownloads", create: true
    config.vm.synced_folder ".", "/vagrant", disabled: true

    config.vm.provision "shell", inline: "C:/freyja-provisioner.ps1"
end
